// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4BQgEBCQZI6IcQ2VgG5i2YMeni4Pselc',
    appId: '1:281433613028:web:072a814d38bab49619c2f1',
    messagingSenderId: '281433613028',
    projectId: 'addmin-212d3',
    authDomain: 'addmin-212d3.firebaseapp.com',
    databaseURL: 'https://addmin-212d3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'addmin-212d3.firebasestorage.app',
    measurementId: 'G-9SVVBT86HC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfC8Qg1OtQ5fL5eGZrEJlhL2OS_33hwqI',
    appId: '1:281433613028:android:ff069d663e41e43f19c2f1',
    messagingSenderId: '281433613028',
    projectId: 'addmin-212d3',
    databaseURL: 'https://addmin-212d3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'addmin-212d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0bqlXTE9Yy7Qv2PCen1um6l3sIaXDo7w',
    appId: '1:281433613028:ios:aa915f6016e54a2719c2f1',
    messagingSenderId: '281433613028',
    projectId: 'addmin-212d3',
    databaseURL: 'https://addmin-212d3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'addmin-212d3.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4BQgEBCQZI6IcQ2VgG5i2YMeni4Pselc',
    appId: '1:281433613028:web:deaa6e3e5cdfaa2819c2f1',
    messagingSenderId: '281433613028',
    projectId: 'addmin-212d3',
    authDomain: 'addmin-212d3.firebaseapp.com',
    databaseURL: 'https://addmin-212d3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'addmin-212d3.firebasestorage.app',
    measurementId: 'G-ERS7WTKPG8',
  );
}
